#!/bin/sh
#
# Local hook to enforce commit message format as described here https://github.com/angular/angular/blob/17.3.4/CONTRIBUTING.md#-commit-message-format
#  
#
test -n "$(grep -E '^((revert)|((build|ci|docs|feat|fix|perf|refactor|test)\(.+\))): .{7,}' ${1})" || {
    echo >&2 "ERROR: Commit message does not follow the commit styleguide."
    echo >&2 "       Please check the following guide:"
    echo >&2 "           https://github.com/angular/angular/blob/17.3.4/CONTRIBUTING.md#-commit-message-format"
    echo >&2 ""
    echo >&2 "SYNTAX:"
    echo >&2 "    <type>(<scope>): <subject>"
    echo >&2 ""
    echo >&2 "    <descriptive body>"
    echo >&2 ""
    echo >&2 "TYPE:"
    echo >&2 "    build: Changes that affect the build system or external dependencies"
    echo >&2 "    ci: Changes to our CI configuration files and scripts"
    echo >&2 "    docs: Documentation only changes"
    echo >&2 "    feat: A new feature"
    echo >&2 "    fix: A bug fix"
    echo >&2 "    perf: A code change that improves performance"
    echo >&2 "    refactor: A code change that neither fixes a bug nor adds a feature"
    echo >&2 "    test: Adding missing tests or correcting existing tests"
    echo >&2 ""
    exit 1
}